
baseurl = "https://popey.com/blog"
title = "Alan Pope's blog"
languageCode = "en-gb"
theme = "beautifulhugo"
#disqusShortname="popey"
enableGitInfo = true

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Alan Pope's blog"
    description = "A bit of personal space for writing"
    github = "https://github.com/popey/popey.com-blog"
    twitter = "https://twitter.com/popey"
    email = "alan@popey.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    #style = "dark"
    commit = "https://github.com/popey/popey.com-blog/tree/"

[Params.giscus]
    repo = "popey/popey.com-blog"
    repoID = "MDEwOlJlcG9zaXRvcnkzMjIzMjI2MTE="
    category = "General"
    categoryID = "DIC_kwDOEzZAs84CTEsk"
    mapping = "title"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "dark"
    lang = "en"
    loading = "lazy"

[Permalinks]
    post = "/:year/:month/:filename/"

[[menu.main]]
    url = "https://github.com/popey/popey.com-blog"
    name = "Site Source"
    weight = 9

[[menu.main]]
    url = "about"
    name = "About"
    weight = 6

[[menu.main]]
    url = "contact"
    name = "Contact"
    weight = 7

[[menu.main]]
    url = "index.xml"
    name = "RSS"
    weight = 8
